### ISSUE TITLE
Allow drawing of basic shapes onto the UI field from code

### ISSUE THREAD

**Issue by JNeiger** [SSL-A-Team/software#5]
Semi blocked on #4 

Allow code to draw text, lines, curves, shapes etc with unique colors and opacity onto the UI from code. It would be ideal if one can change parameters on already drawn shapes.

For example: one use case may be to draw the trajectory of each robot onto the field. Each robot will only have on trajectory so if in code, we could choose to redraw that specific already drawn trajectory with different positions instead of drawing another trajectory overtop.

**Comment by chachmu** [comment]
I know at one point we had a discussion about using the ROS visualization_msgs for specifying UI overlays but as far as I can tell only the [ImageMarker](http://docs.ros.org/en/api/visualization_msgs/html/msg/ImageMarker.html) message would be useful for 2d and even it only supports circles, line_strips, and polygons.

It might be easier to find or make a different alternative so we can have predefined options for other shapes like rectangles and splines.

**Comment by JNeiger** [comment]
I'm fine going custom. I think as long as we support basic shapes, trajectories, text(?), and maybe mesh overlays (think plotting shot chance as a function of position), we should be all good.

**Comment by chachmu** [comment]
Closed by #37
