### ISSUE TITLE
Improve robot to behavior assignment

### ISSUE THREAD

**Issue by JNeiger** [SSL-A-Team/software#97]
[Current implementation](https://github.com/SSL-A-Team/software/blob/dev/jneiger/goalie_shot_ai/ateam_ai/src/behavior/behavior_realization.cpp#L51-L73) is just in order of robot id's. We should optimize for shortest total time to complete required behaviors, then shortest total time to complete the rest of the behaviors (or something)

**Comment by barulicm** [comment]
This was resolved with @fourpenny's assignment rewrite.
